# Consumindo APIs simples

Aqui vamos utilizar a API do BrasilAPI. Ela é uma API que fornece dados públicos do Brasil. Site: https://brasilapi.com.br/

Bibliotecas que vamos utilizar:

- requests

```
pip install requests
```

- pandas

```
pip install pandas
```

A biblioteca requests é utilizada para fazer requisições HTTP. A biblioteca pandas é utilizada para manipular dados.

## Passos de consumo de uma API


1. **Estudo da Documentação:**
   - Antes de tudo, familiarize-se com a documentação da API. Ela fornecerá informações sobre como a API funciona, seus endpoints, parâmetros disponíveis, formatos de resposta e muito mais.
   
2. **Entendimento dos Status Codes:**
   - Compreenda os status codes HTTP para interpretar as respostas da API. Isso ajudará a diagnosticar problemas e entender o status das suas requisições.

3. **Registro e Autenticação:**
   - Muitas APIs exigem que você se registre para obter uma chave de API ou token. Esse token é usado para autenticar suas requisições e, muitas vezes, para rastrear e limitar seu uso.

4. **Configuração do Ambiente:**
   - Configure seu ambiente de desenvolvimento. Isso pode envolver a instalação de bibliotecas ou ferramentas específicas, como `requests` em Python.

5. **Realização de Requisições Teste:**
   - Comece fazendo requisições simples para testar a conexão e entender a estrutura das respostas. Isso pode envolver a obtenção de um único item ou listar vários itens.

6. **Tratamento de Parâmetros e Cabeçalhos:**
   - Aprenda a enviar parâmetros (por exemplo, para filtrar resultados) e a definir cabeçalhos adequados (como tokens de autenticação ou informações de tipo de conteúdo).

7. **Paginação e Limites:**
   - Entenda como a API lida com grandes conjuntos de dados. Muitas APIs paginam os resultados ou impõem limites de quantos itens você pode solicitar de uma vez.

8. **Tratamento de Respostas e Erros:**
   - Analise as respostas, extraia os dados necessários e implemente tratamentos de erro adequados para lidar com possíveis falhas ou limitações.

9. **Integração com Aplicações:**
   - Integre os dados ou funcionalidades da API em sua aplicação, seja ela um site, aplicativo móvel ou sistema backend.

10. **Otimizações (Cache, Rate Limiting, etc.):**
   - Implemente otimizações, como caching de respostas frequentes, para melhorar o desempenho e garantir que você não exceda os limites da API.

11. **Monitoramento e Manutenção:**
   - Monitore o uso da API, verifique regularmente a saúde das requisições e esteja atento a quaisquer mudanças ou atualizações na API.


## Status Codes


### **O que são status codes?**

Status codes, ou códigos de status, são códigos de três dígitos que os servidores HTTP enviam para indicar o resultado de uma requisição feita por um cliente. Eles informam ao cliente se a requisição foi bem-sucedida, se houve algum erro, ou se é necessário realizar alguma ação adicional. Esses códigos são padronizados e fazem parte do protocolo HTTP, permitindo que clientes e servidores de diferentes implementações se comuniquem de forma eficaz.

### **Principais status codes e seus significados**

- **2xx: Sucesso**
  - **200 OK:** A requisição foi bem-sucedida. O resultado depende do método HTTP utilizado.
  - **201 Created:** A requisição foi bem-sucedida e um novo recurso foi criado como resultado.
  - **204 No Content:** A requisição foi bem-sucedida, mas não há conteúdo para enviar na resposta.

- **3xx: Redirecionamento**
  - **301 Moved Permanently:** O recurso solicitado foi movido permanentemente para uma nova URL.
  - **302 Found (ou Moved Temporarily):** O recurso solicitado foi movido temporariamente para uma nova URL.
  - **304 Not Modified:** O recurso não foi modificado desde a última requisição.

- **4xx: Erros do cliente**
  - **400 Bad Request:** A requisição não pode ser processada devido a um erro do cliente, como sintaxe de requisição inválida.
  - **401 Unauthorized:** O cliente não está autenticado para acessar o recurso solicitado.
  - **403 Forbidden:** O cliente está autenticado, mas não tem permissão para acessar o recurso.
  - **404 Not Found:** O recurso solicitado não foi encontrado no servidor.

- **5xx: Erros do servidor**
  - **500 Internal Server Error:** O servidor encontrou uma situação que não sabe como lidar.
  - **502 Bad Gateway:** O servidor, ao atuar como gateway ou proxy, recebeu uma resposta inválida do servidor upstream.
  - **503 Service Unavailable:** O servidor não está pronto para lidar com a requisição, geralmente devido a manutenção ou sobrecarga.

### **Como lidar com diferentes status codes em Python**

Ao usar a biblioteca `requests` em Python, você pode verificar o status code de uma resposta usando o atributo `status_code` do objeto de resposta. Aqui está um exemplo básico de como lidar com diferentes status codes:

```python
import requests

response = requests.get('https://api.exemplo.com/dados')

if response.status_code == 200:
    print("Requisição bem-sucedida!")
    data = response.json()
elif response.status_code == 404:
    print("Erro: Recurso não encontrado.")
elif response.status_code >= 500:
    print("Erro no servidor. Tente novamente mais tarde.")
else:
    print(f"Erro desconhecido. Status code: {response.status_code}")
```

É uma boa prática sempre verificar o status code ao fazer requisições para lidar adequadamente com possíveis erros e garantir que sua aplicação continue funcionando de forma suave.

## Dados de Bancos

In [3]:
import requests

URL_BANCOS = "https://brasilapi.com.br/api/banks/v1"

resposta_bancos = requests.get(URL_BANCOS)

resposta_bancos.status_code

200

In [6]:
resposta_bancos.headers

{'Date': 'Thu, 16 Apr 2026 12:34:02 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'Age': '13431', 'Cache-Control': 'max-age=0, public', 'Report-To': '{"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=TLCapAn%2FHsMJxbtakjAZ0F%2BbC3p5R0TSXpVuEXa7FD8PKH45ltRfz49bzPiWrqp9Pi9JdaJOELSlMoJ6r0GISO4ZqVn9Ov6uzFk6pAusaV1tqSLR%2F%2FtEDM4C%2FFwAZYawL8EObBQMx7jpVk%2FKLc6H"}]}', 'etag': 'W/"4q27w4ow2v166m"', 'Server': 'cloudflare', 'strict-transport-security': 'max-age=63072000', 'x-matched-path': '/api/banks/v1', 'x-vercel-cache': 'HIT', 'x-vercel-id': 'gru1::sfo1::f9kfr-1776342842971-3f79a430bdc9', 'cf-cache-status': 'DYNAMIC', 'vary': 'accept-encoding', 'Nel': '{"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}', 'Content-Encoding': 'gzip', 'CF-RAY': '9ed338d08badbba0-GRU', 'alt-svc': 'h3=":443"; ma=86400'}

Observe o valor do cabeçalho `Content-Type`. Ele indica que o conteúdo da resposta está no formato JSON. Isso é útil para saber como processar a resposta e extrair os dados necessários.


### O que é JSON?


JSON (JavaScript Object Notation) é um formato de dados muito utilizado para transmitir dados estruturados pela web. Ele é baseado na sintaxe de objetos JavaScript, mas pode ser lido e interpretado por muitas linguagens de programação modernas, como Python.

O JSON é um formato de dados muito popular, pois é fácil de ler e escrever, além de ser leve e independente de linguagem. Ele é frequentemente usado para transmitir dados entre um servidor e um cliente da web.

Aqui está um exemplo de um objeto JSON:

```json
{
    "nome": "João",
    "idade": 30,
    "cidade": "São Paulo"
}
```

Observe que o JSON consiste em pares de chave-valor, onde as chaves são sempre strings e os valores podem ser strings, números, booleanos, objetos ou arrays. Os objetos JSON são delimitados por chaves `{}` e os arrays JSON são delimitados por colchetes `[]`.

Aqui está um exemplo de um array JSON:

```json
[
    {
        "nome": "João",
        "idade": 30,
        "cidade": "São Paulo"
    },
    {
        "nome": "Maria",
        "idade": 27,
        "cidade": "Rio de Janeiro"
    },
    {
        "nome": "Pedro",
        "idade": 35,
        "cidade": "Belo Horizonte"
    }
]
```

Qual é a diferença entre objetos e arrays JSON? Objetos JSON são delimitados por chaves `{}` e contêm pares de chave-valor. Arrays JSON são delimitados por colchetes `[]` e contêm uma lista de valores separados por vírgula. Objetos JSON são usados para representar registros individuais, enquanto arrays JSON são usados para representar uma lista de registros.

E qual é a diferença entre JSON e um dicionário do Python? JSON é um formato de dados independente de linguagem, enquanto um dicionário do Python é um tipo de dados específico da linguagem Python. JSON é uma string que pode ser lida e interpretada por muitas linguagens de programação modernas, incluindo Python. Dicionários do Python são estruturas de dados nativas da linguagem Python. JSON e dicionários do Python são semelhantes, mas não são a mesma coisa.

- `ispb` é o Identificador do Sistema de Pagamentos Brasileiros, número que identifica as instituições financeiras no sistema de transferência de reserva do Banco Central do Brasil.
- `code` é o código COMPE da instituição, sendo COMPE referente a Centralizadora da Compensação de Cheques, responsável por processar a compensação interbancária dos cheques e demais operações de transferências.
- `fullName` é o nome completo do banco.
- `name` é o nome abreviado do banco.

In [8]:
bancos = resposta_bancos.json()

bancos[:5]

[{'ispb': '00000000',
  'name': 'BCO DO BRASIL S.A.',
  'code': 1,
  'fullName': 'Banco do Brasil S.A.'},
 {'ispb': '00000208',
  'name': 'BRB - BCO DE BRASILIA S.A.',
  'code': 70,
  'fullName': 'BRB - BANCO DE BRASILIA S.A.'},
 {'ispb': '00038121',
  'name': 'Selic',
  'code': None,
  'fullName': 'Banco Central do Brasil - Selic'},
 {'ispb': '00038166',
  'name': 'Bacen',
  'code': None,
  'fullName': 'Banco Central do Brasil'},
 {'ispb': '00122327',
  'name': 'SANTINVEST S.A. - CFI',
  'code': 539,
  'fullName': 'SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTOS'}]

In [13]:
from pprint import pprint

pprint(bancos[:5])

[{'code': 1,
  'fullName': 'Banco do Brasil S.A.',
  'ispb': '00000000',
  'name': 'BCO DO BRASIL S.A.'},
 {'code': 70,
  'fullName': 'BRB - BANCO DE BRASILIA S.A.',
  'ispb': '00000208',
  'name': 'BRB - BCO DE BRASILIA S.A.'},
 {'code': None,
  'fullName': 'Banco Central do Brasil - Selic',
  'ispb': '00038121',
  'name': 'Selic'},
 {'code': None,
  'fullName': 'Banco Central do Brasil',
  'ispb': '00038166',
  'name': 'Bacen'},
 {'code': 539,
  'fullName': 'SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTOS',
  'ispb': '00122327',
  'name': 'SANTINVEST S.A. - CFI'}]

In [12]:
from pprint import pprint

pprint(bancos[5:])

[{'code': 430,
  'fullName': 'COOPERATIVA DE CREDITO RURAL SEARA - CREDISEARA',
  'ispb': '00204963',
  'name': 'CCR SEARA'},
 {'code': 272,
  'fullName': 'AGK CORRETORA DE CAMBIO S.A.',
  'ispb': '00250699',
  'name': 'AGK CC S.A.'},
 {'code': 136,
  'fullName': 'COOPERATIVA CENTRAL DE CRÉDITO UNICRED DO BRASIL - UNICRED DO '
              'BRASIL',
  'ispb': '00315557',
  'name': 'UNICRED DO BRASIL'},
 {'code': 407,
  'fullName': 'SEFER INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES '
              'MOBILIÁRIOS LTDA',
  'ispb': '00329598',
  'name': 'SEFER INVESTIMENTOS DTVM LTDA'},
 {'code': 104,
  'fullName': 'CAIXA ECONOMICA FEDERAL',
  'ispb': '00360305',
  'name': 'CAIXA ECONOMICA FEDERAL'},
 {'code': None,
  'fullName': 'Secretaria do Tesouro Nacional - STN',
  'ispb': '00394460',
  'name': 'STN'},
 {'code': 714,
  'fullName': 'FINAMAX S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTO',
  'ispb': '00411939',
  'name': 'FINAMAX S.A. CFI'},
 {'code': 77,
  'fullName': 'Banco Inter S.A.',
  'ispb': '00416968',
  'name': 'BANCO INTER'},
 {'code': 423,
  'fullName': 'COLUNA S/A DISTRIBUIDORA DE TITULOS E VALORES MOBILIÁRIOS',
  'ispb': '00460065',
  'name': 'COLUNA S.A. DTVM'},
 {'code': 741,
  'fullName': 'BANCO RIBEIRAO PRETO S.A.',
  'ispb': '00517645',
  'name': 'BCO RIBEIRAO PRETO S.A.'},
 {'code': 330,
  'fullName': 'BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A.',
  'ispb': '00556603',
  'name': 'BANCO BARI S.A.'},
 {'code': 534,
  'fullName': 'EWALLY INSTITUIÇÃO DE PAGAMENTO S.A.',
  'ispb': '00714671',
  'name': 'EWALLY IP S.A.'},
 {'code': 743,
  'fullName': 'Banco Semear S.A.',
  'ispb': '00795423',
  'name': 'BANCO SEMEAR'},
 {'code': 100,
  'fullName': 'Planner Corretora de Valores S.A.',
  'ispb': '00806535',
  'name': 'PLANNER CV S.A.'},
 {'code': 541,
  'fullName': 'FUNDO GARANTIDOR DE CREDITOS - FGC',
  'ispb': '00954288',
  'name': 'FDO GARANTIDOR CRÉDITOS'},
 {'code': 96,
  'fullName': 'Banco B3 S.A.',
  'ispb': '00997185',
  'name': 'BCO B3 S.A.'},
 {'code': 747,
  'fullName': 'Banco Rabobank International Brasil S.A.',
  'ispb': '01023570',
  'name': 'BCO RABOBANK INTL BRASIL S.A.'},
 {'code': 362,
  'fullName': 'CIELO S.A. - INSTITUIÇÃO DE PAGAMENTO',
  'ispb': '01027058',
  'name': 'CIELO IP S.A.'},
 {'code': 322,
  'fullName': 'Cooperativa de Crédito Rural de Abelardo Luz - '
              'Sulcredi/Crediluz',
  'ispb': '01073966',
  'name': 'CCR DE ABELARDO LUZ'},
 {'code': 748,
  'fullName': 'BANCO COOPERATIVO SICREDI S.A.',
  'ispb': '01181521',
  'name': 'BCO COOPERATIVO SICREDI S.A.'},
 {'code': 350,
  'fullName': 'COOPERATIVA DE CRÉDITO, POUPANÇA E SERVIÇOS FINANCEIROS DE '
              'AGRICULTORES E AEROPORTUÁRIOS DO BRASIL - CREHNOR',
  'ispb': '01330387',
  'name': 'COOP DE AGRICULTORES E AEROPORTUÁRIOS DO BRASIL'},
 {'code': 752,
  'fullName': 'Banco BNP Paribas Brasil S.A.',
  'ispb': '01522368',
  'name': 'BCO BNP PARIBAS BRASIL S A'},
 {'code': 379,
  'fullName': 'COOPERFORTE COOPERATIVA DE CRÉDITO E INVESTIMENTOS LTDA',
  'ispb': '01658426',
  'name': 'COOP COOPERFORTE LTDA.'},
 {'code': 399,
  'fullName': 'Kirton Bank S.A. - Banco Múltiplo',
  'ispb': '01701201',
  'name': 'Kirton Bank'},
 {'code': 378,
  'fullName': 'BANCO BRASILEIRO DE CRÉDITO SOCIEDADE ANÔNIMA',
  'ispb': '01852137',
  'name': 'BCO BRASILEIRO DE CRÉDITO S.A.'},
 {'code': 413,
  'fullName': 'BANCO BV S.A.',
  'ispb': '01858774',
  'name': 'BCO BV S.A.'},
 {'code': 756,
  'fullName': 'BANCO COOPERATIVO SICOOB S.A. - BANCO SICOOB',
  'ispb': '02038232',
  'name': 'BANCO SICOOB S.A.'},
 {'code': 360,
  'fullName': 'TRINUS CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS '
              'S.A.',
  'ispb': '02276653',
  'name': 'TRINUS CAPITAL DTVM'},
 {'code': 757,
  'fullName': 'BANCO KEB HANA DO BRASIL S.A.',
  'ispb': '02318507',
  'name': 'BCO KEB HANA DO BRASIL S.A.'},
 {'code': 102,
  'fullName': 'XP INVESTIMENTOS CORRETORA DE CÂMBIO,TÍTULOS E VALORES '
              'MOBILIÁRIOS S/A',
  'ispb': '02332886',
  'name': 'XP INVESTIMENTOS CCTVM S/A'},
 {'code': 84,
  'fullName': 'SISPRIME DO BRASIL - COOPERATIVA DE CRÉDITO',
  'ispb': '02398976',
  'name': 'SISPRIME DO BRASIL - COOP'},
 {'code': 591,
  'fullName': 'BANVOX DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  'ispb': '02671743',
  'name': 'BANVOX DTVM'},
 {'code': 555,
  'fullName': 'PAN FINANCEIRA S.A. - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E '
              'INVESTIMENTOS',
  'ispb': '02682287',
  'name': 'PAN FINAN'},
 {'code': 180,
  'fullName': 'CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES '
              'MOBILIÁRIOS LTDA',
  'ispb': '02685483',
  'name': 'CM CAPITAL MARKETS CCTVM LTDA'},
 {'code': 66,
  'fullName': 'BANCO MORGAN STANLEY S.A.',
  'ispb': '02801938',
  'name': 'BCO MORGAN STANLEY S.A.'},
 {'code': 15,
  'fullName': 'UBS BB CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS S.A.',
  'ispb': '02819125',
  'name': 'UBS BB CCTVM S.A.'},
 {'code': 143,
  'fullName': 'INTEX BANK BANCO DE CÂMBIO S.A.',
  'ispb': '02992317',
  'name': 'INTEX BANK BCO DE CÂMBIO S.A.'},
 {'code': None,
  'fullName': 'CIP S.A',
  'ispb': '02992335',
  'name': 'CIP SA Siloc'},
 {'code': 74,
  'fullName': 'Banco J. Safra S.A.',
  'ispb': '03017677',
  'name': 'BCO. J.SAFRA S.A.'},
 {'code': 99,
  'fullName': 'UNIPRIME CENTRAL NACIONAL - CENTRAL NACIONAL DE COOPERATIVA DE '
              'CREDITO',
  'ispb': '03046391',
  'name': 'UNIPRIME COOPCENTRAL LTDA.'},
 {'code': 387,
  'fullName': 'Banco Toyota do Brasil S.A.',
  'ispb': '03215790',
  'name': 'BCO TOYOTA DO BRASIL S.A.'},
 {'code': 326,
  'fullName': 'PARATI - CREDITO, FINANCIAMENTO E INVESTIMENTO S.A.',
  'ispb': '03311443',
  'name': 'PARATI - CFI S.A.'},
 {'code': 25,
  'fullName': 'Banco Alfa S.A.',
  'ispb': '03323840',
  'name': 'BCO ALFA S.A.'},
 {'code': 75,
  'fullName': 'BANCO ABN AMRO CLEARING S.A.',
  'ispb': '03532415',
  'name': 'BANCO ABN AMRO CLEARING S.A.'},
 {'code': 40,
  'fullName': 'Banco Cargill S.A.',
  'ispb': '03609817',
  'name': 'BCO CARGILL S.A.'},
 {'code': 307,
  'fullName': 'Terra Investimentos Distribuidora de Títulos e Valores '
              'Mobiliários Ltda.',
  'ispb': '03751794',
  'name': 'TERRA INVESTIMENTOS DTVM'},
 {'code': 517,
  'fullName': 'PAGUEVELOZ INSTITUIÇÃO DE PAGAMENTO LTDA.',
  'ispb': '03816413',
  'name': 'PAGUEVELOZ IP LTDA.'},
 {'code': 385,
  'fullName': 'COOPERATIVA DE ECONOMIA E CREDITO MUTUO DOS TRABALHADORES '
              'PORTUARIOS DA GRANDE VITORIA - CREDESTIVA.',
  'ispb': '03844699',
  'name': 'CECM DOS TRAB.PORT. DA G.VITOR'},
 {'code': 425,
  'fullName': 'SOCINAL S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
  'ispb': '03881423',
  'name': 'SOCINAL S.A. CFI'},
 {'code': 190,
  'fullName': 'SERVICOOP - COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS '
              'ESTADUAIS E MUNICIPAIS DO RIO GRANDE DO SUL',
  'ispb': '03973814',
  'name': 'SERVICOOP'},
 {'code': 296,
  'fullName': 'OZ CORRETORA DE CÂMBIO S.A.',
  'ispb': '04062902',
  'name': 'OZ CORRETORA DE CÂMBIO S.A.'},
 {'code': 63,
  'fullName': 'Banco Bradescard S.A.',
  'ispb': '04184779',
  'name': 'BANCO BRADESCARD'},
 {'code': 191,
  'fullName': 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.',
  'ispb': '04257795',
  'name': 'NOVA FUTURA CTVM LTDA.'},
 {'code': 764,
  'fullName': 'INDEPENDÊNCIA COOPERATIVA DE CRÉDITO E INVESTIMENTO - '
              'INDEPENDÊNCIA COOPERATIVA DE CRÉDITO',
  'ispb': '04306351',
  'name': 'INDEPENDÊNCIA CC'},
 {'code': 382,
  'fullName': 'FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA '
              'DE PEQUENO PORTE LIMITADA.',
  'ispb': '04307598',
  'name': 'FIDUCIA SCMEPP LTDA'},
 {'code': 64,
  'fullName': 'GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A.',
  'ispb': '04332281',
  'name': 'GOLDMAN SACHS DO BRASIL BM S.A'},
 {'code': None,
  'fullName': 'CIP S.A',
  'ispb': '04391007',
  'name': 'CIP SA Sitraf'},
 {'code': 97,
  'fullName': 'Credisis - Central de Cooperativas de Crédito Ltda.',
  'ispb': '04632856',
  'name': 'CREDISIS - CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.'},
 {'code': 16,
  'fullName': 'COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE '
              'SANTA CATARINA E RIO GRANDE DO SUL - SICOOB CREDITRAN',
  'ispb': '04715685',
  'name': 'CCM DESP TRÂNS SC E RS'},
 {'code': 299,
  'fullName': 'BANCO AFINZ S.A. - BANCO MÚLTIPLO',
  'ispb': '04814563',
  'name': 'BCO AFINZ S.A. - BM'},
 {'code': 540,
  'fullName': 'HBI SOCIEDADE DE CRÉDITO DIRETO S/A.',
  'ispb': '04849745',
  'name': 'HBI SCD'},
 {'code': 468,
  'fullName': 'PORTOSEG S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTO',
  'ispb': '04862600',
  'name': 'PORTOSEG S.A. CFI'},
 {'code': 12,
  'fullName': 'Banco Inbursa S.A.',
  'ispb': '04866275',
  'name': 'BANCO INBURSA'},
 {'code': 3,
  'fullName': 'BANCO DA AMAZONIA S.A.',
  'ispb': '04902979',
  'name': 'BCO DA AMAZONIA S.A.'},
 {'code': 60,
  'fullName': 'CONFIDENCE SOCIEDADE CORRETORA DE CAMBIO S.A.',
  'ispb': '04913129',
  'name': 'CONFIDENCE CC S.A.'},
 {'code': 37,
  'fullName': 'Banco do Estado do Pará S.A.',
  'ispb': '04913711',
  'name': 'BCO DO EST. DO PA S.A.'},
 {'code': 411,
  'fullName': 'Via Certa Financiadora S.A. - Crédito, Financiamento e '
              'Investimentos',
  'ispb': '05192316',
  'name': 'VIA CERTA FINANCIADORA S.A. - CFI'},
 {'code': 359,
  'fullName': 'ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A',
  'ispb': '05351887',
  'name': 'ZEMA CFI S/A'},
 {'code': 159,
  'fullName': 'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor',
  'ispb': '05442029',
  'name': 'CASA CREDITO S.A. SCM'},
 {'code': 85,
  'fullName': 'Cooperativa Central de Crédito - Ailos',
  'ispb': '05463212',
  'name': 'COOPCENTRAL AILOS'},
 {'code': 400,
  'fullName': 'COOPERATIVA DE CRÉDITO, POUPANÇA E SERVIÇOS FINANCEIROS',
  'ispb': '05491616',
  'name': 'COOP CREDITAG'},
 {'code': 410,
  'fullName': 'PLANNER SOCIEDADE DE CRÉDITO DIRETO S.A.',
  'ispb': '05684234',
  'name': 'PLANNER SOCIEDADE DE CRÉDITO DIRETO'},
 {'code': 328,
  'fullName': 'COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS FABRICANTES DE '
              'CALÇADOS DE SAPIRANGA LTDA.',
  'ispb': '05841967',
  'name': 'CECM FABRIC CALÇADOS SAPIRANGA'},
 {'code': 548,
  'fullName': 'RPW S/A SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
  'ispb': '06249129',
  'name': 'RPW S.A. SCFI'},
 {'code': 36,
  'fullName': 'Banco Bradesco BBI S.A.',
  'ispb': '06271464',
  'name': 'BCO BBI S.A.'},
 {'code': 469,
  'fullName': 'PICPAY INVEST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS '
              'LTDA',
  'ispb': '07138049',
  'name': 'PICPAY INVEST'},
 {'code': 394,
  'fullName': 'Banco Bradesco Financiamentos S.A.',
  'ispb': '07207996',
  'name': 'BCO BRADESCO FINANC. S.A.'},
 {'code': 4,
  'fullName': 'Banco do Nordeste do Brasil S.A.',
  'ispb': '07237373',
  'name': 'BCO DO NORDESTE DO BRASIL S.A.'},
 {'code': 458,
  'fullName': 'HEDGE INVESTMENTS DISTRIBUIDORA DE TÍTULOS E VALORES '
              'MOBILIÁRIOS LTDA.',
  'ispb': '07253654',
  'name': 'HEDGE INVESTMENTS DTVM LTDA.'},
 {'code': 320,
  'fullName': 'BANK OF CHINA (BRASIL) BANCO MÚLTIPLO S/A',
  'ispb': '07450604',
  'name': 'BOC BRASIL'},
 {'code': 189,
  'fullName': 'HS FINANCEIRA S/A CREDITO, FINANCIAMENTO E INVESTIMENTOS',
  'ispb': '07512441',
  'name': 'HS FINANCEIRA'},
 {'code': 105,
  'fullName': 'Lecca Crédito, Financiamento e Investimento S/A',
  'ispb': '07652226',
  'name': 'LECCA CFI S.A.'},
 {'code': 76,
  'fullName': 'Banco KDB do Brasil S.A.',
  'ispb': '07656500',
  'name': 'BCO KDB BRASIL S.A.'},
 {'code': 82,
  'fullName': 'BANCO TOPÁZIO S.A.',
  'ispb': '07679404',
  'name': 'BANCO TOPÁZIO S.A.'},
 {'code': 312,
  'fullName': 'HSCM - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE '
              'PEQUENO PORTE LTDA.',
  'ispb': '07693858',
  'name': 'HSCM SCMEPP LTDA.'},
 {'code': 195,
  'fullName': 'VALOR S/A SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
  'ispb': '07799277',
  'name': 'VALOR S/A SCFI'},
 {'code': 93,
  'fullName': 'PÓLOCRED   SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À '
              'EMPRESA DE PEQUENO PORTE LTDA.',
  'ispb': '07945233',
  'name': 'POLOCRED SCMEPP LTDA.'},
 {'code': 391,
  'fullName': 'COOPERATIVA DE CREDITO RURAL DE IBIAM - SULCREDI/IBIAM',
  'ispb': '08240446',
  'name': 'CCR DE IBIAM'},
 {'code': 273,
  'fullName': 'COOPERATIVA DE CREDITO SULCREDI AMPLEA',
  'ispb': '08253539',
  'name': 'COOP SULCREDI AMPLEA'},
 {'code': 368,
  'fullName': 'Banco CSF S.A.',
  'ispb': '08357240',
  'name': 'BCO CSF S.A.'},
 {'code': 673,
  'fullName': 'COOPERATIVA DE CRÉDITO RURAL DO AGRESTE ALAGOANO - COOPERAGRE',
  'ispb': '08482873',
  'name': 'CCR DO AGRESTE ALAGOANO'},
 {'code': 290,
  'fullName': 'PAGSEGURO INTERNET INSTITUIÇÃO DE PAGAMENTO S.A.',
  'ispb': '08561701',
  'name': 'PAGSEGURO INTERNET IP S.A.'},
 {'code': 259,
  'fullName': 'MONEYCORP BANCO DE CÂMBIO S.A.',
  'ispb': '08609934',
  'name': 'MONEYCORP BCO DE CÂMBIO S.A.'},
 {'code': 395,
  'fullName': "F.D'GOLD - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.",
  'ispb': '08673569',
  'name': 'F D GOLD DTVM LTDA'},
 {'code': 364,
  'fullName': 'EFÍ S.A. - INSTITUIÇÃO DE PAGAMENTO',
  'ispb': '09089356',
  'name': 'EFÍ S.A. - IP'},
 {'code': 157,
  'fullName': 'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.',
  'ispb': '09105360',
  'name': 'ICAP DO BRASIL CTVM LTDA.'},
 {'code': 183,
  'fullName': 'SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À '
              'EMPRESA DE PEQUENO PORTE',
  'ispb': '09210106',
  'name': 'SOCRED SA - SCMEPP'},
 {'code': 14,
  'fullName': 'STATE STREET BRASIL S.A. - BANCO COMERCIAL',
  'ispb': '09274232',
  'name': 'STATE STREET BR S.A. BCO COMERCIAL'},
 {'code': 130,
  'fullName': 'CARUANA S.A. - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E '
              'INVESTIMENTO',
  'ispb': '09313766',
  'name': 'CARUANA SCFI'},
 {'code': 358,
  'fullName': 'MIDWAY S.A. - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E '
              'INVESTIMENTO',
  'ispb': '09464032',
  'name': 'MIDWAY S.A. - SCFI'},
 {'code': 127,
  'fullName': 'Codepe Corretora de Valores e Câmbio S.A.',
  'ispb': '09512542',
  'name': 'CODEPE CVC S.A.'},
 {'code': 79,
  'fullName': 'PICPAY BANK - BANCO MÚLTIPLO S.A',
  'ispb': '09516419',
  'name': 'PICPAY BANK - BANCO MÚLTIPLO S.A'},
 {'code': 141,
  'fullName': 'BANCO MASTER DE INVESTIMENTO S.A. - EM LIQUIDAÇÃO EXTRAJUDICIAL',
  'ispb': '09526594',
  'name': 'MASTER BI S.A. - EM LIQUIDAÇÃO EXTRAJUDICIAL'},
 {'code': 81,
  'fullName': 'BancoSeguro S.A.',
  'ispb': '10264663',
  'name': 'BANCOSEGURO S.A.'},
 {'code': 475,
  'fullName': 'Banco Yamaha Motor do Brasil S.A.',
  'ispb': '10371492',
  'name': 'BCO YAMAHA MOTOR S.A.'},
 {'code': 133,
  'fullName': 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E '
              'ECONOMIA FAMILIAR E SOLIDÁRIA - CRESOL CONFEDERAÇÃO',
  'ispb': '10398952',
  'name': 'CRESOL CONFEDERAÇÃO'},
 {'code': 703,
  'fullName': 'GETNET ADQUIRÊNCIA E SERVIÇOS PARA MEIOS DE PAGAMENTO S.A. '
              'INSTITUIÇÃO DE PAGAMENTO',
  'ispb': '10440482',
  'name': 'GETNET IP'},
 {'code': 323,
  'fullName': 'MERCADO PAGO INSTITUIÇÃO DE PAGAMENTO LTDA.',
  'ispb': '10573521',
  'name': 'MERCADO PAGO IP LTDA.'},
 {'code': 577,
  'fullName': 'DESENVOLVE SP - AGÊNCIA DE FOMENTO DO ESTADO DE SÃO PAULO S.A.',
  'ispb': '10663610',
  'name': 'AF DESENVOLVE SP S.A.'},
 {'code': 121,
  'fullName': 'Banco Agibank S.A.',
  'ispb': '10664513',
  'name': 'BCO AGIBANK S.A.'},
 {'code': 83,
  'fullName': 'Banco da China Brasil S.A.',
  'ispb': '10690848',
  'name': 'BCO DA CHINA BRASIL S.A.'},
 {'code': 138,
  'fullName': 'Get Money Corretora de Câmbio S.A.',
  'ispb': '10853017',
  'name': 'GET MONEY CC LTDA'},
 {'code': 24,
  'fullName': 'Banco Bandepe S.A.',
  'ispb': '10866788',
  'name': 'BCO BANDEPE S.A.'},
 {'code': 384,
  'fullName': 'GLOBAL FINANÇAS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À '
              'EMPRESA DE PEQUENO PORTE LTDA.',
  'ispb': '11165756',
  'name': 'GLOBAL SCM LTDA'},
 {'code': 426,
  'fullName': 'NEON FINANCEIRA - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E '
              'INVESTIMENTO S.A',
  'ispb': '11285104',
  'name': 'NEON FINANCEIRA - SCFI S.A.'},
 {'code': 576,
  'fullName': 'MERCADO BITCOIN INSTITUICAO DE PAGAMENTO LTDA',
  'ispb': '11351086',
  'name': 'MERCADO BITCOIN IP LTDA'},
 {'code': 664,
  'fullName': 'EAGLE INSTITUICAO DE PAGAMENTO LTDA.',
  'ispb': '11414839',
  'name': 'EAGLE IP LTDA.'},
 {'code': 88,
  'fullName': 'BANCO RANDON S.A.',
  'ispb': '11476673',
  'name': 'BANCO RANDON S.A.'},
 {'code': 670,
  'fullName': 'BSN PAGAMENTOS INSTITUIÇÃO DE PAGAMENTO LTDA',
  'ispb': '11491029',
  'name': 'BSN'},
 {'code': 319,
  'fullName': 'OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  'ispb': '11495073',
  'name': 'OM DTVM LTDA'},
 {'code': 274,
  'fullName': 'BMP SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE '
              'PEQUENO PORTE LTDA.',
  'ispb': '11581339',
  'name': 'BMP SCMEPP LTDA'},
 {'code': 95,
  'fullName': 'BANCO TRAVELEX S.A.',
  'ispb': '11703662',
  'name': 'BANCO TRAVELEX S.A.'},
 {'code': 94,
  'fullName': 'Banco Finaxis S.A.',
  'ispb': '11758741',
  'name': 'BANCO FINAXIS'},
 {'code': 478,
  'fullName': 'GAZINCRED S.A. SOCIEDADE DE CRÉDITO, FINANCIAMENTO E '
              'INVESTIMENTO',
  'ispb': '11760553',
  'name': 'GAZINCRED S.A. SCFI'},
 {'code': 276,
  'fullName': 'BANCO SENFF S.A.',
  'ispb': '11970623',
  'name': 'BCO SENFF S.A.'},
 {'code': 780,
  'fullName': 'SAFETYPAY BRASIL INSTITUICAO DE PAGAMENTO LTDA',
  'ispb': '12102128',
  'name': 'SAFETYPAY BRASIL IP LTDA'},
 {'code': 447,
  'fullName': 'MIRAE ASSET (BRASIL) CORRETORA DE CÂMBIO, TÍTULOS  E VALORES '
              'MOBILIÁRIOS LTDA.',
  'ispb': '12392983',
  'name': 'MIRAE ASSET (BRASIL) CCTVM LTDA.'},
 {'code': 569,
  'fullName': 'CONTA PRONTA INSTITUICAO DE PAGAMENTO LTDA',
  'ispb': '12473687',
  'name': 'CONTA PRONTA IP'},
 {'code': 686,
  'fullName': 'BIZ INSTITUIÇÃO DE PAGAMENTO S.A.',
  'ispb': '12481100',
  'name': 'BIZ IP LTDA.'},
 {'code': 47,
  'fullName': 'Banco do Estado de Sergipe S.A.',
  'ispb': '13009717',
  'name': 'BCO DO EST. DE SE S.A.'},
 {'code': 144,
  'fullName': 'EBURY BANCO DE CÂMBIO S.A.',
  'ispb': '13059145',
  'name': 'EBURY BCO DE CÂMBIO S.A.'},
 {'code': 332,
  'fullName': 'ACESSO SOLUÇÕES DE PAGAMENTO S.A. - INSTITUIÇÃO DE PAGAMENTO',
  'ispb': '13140088',
  'name': 'ACESSO SOLUÇÕES DE PAGAMENTO S.A. - INSTITUIÇÃO DE PAGAMENTO'},
 {'code': 450,
  'fullName': 'FITS INSTITUIÇÃO DE PAGAMENTO S.A.',
  'ispb': '13203354',
  'name': 'FITS IP'},
 {'code': 126,
  'fullName': 'BR Partners Banco de Investimento S.A.',
  'ispb': '13220493',
  'name': 'BR PARTNERS BI'},
 {'code': 301,
  'fullName': 'DOCK INSTITUIÇÃO DE PAGAMENTO S.A.',
  'ispb': '13370835',
  'name': 'DOCK IP S.A.'},
 {'code': 173,
  'fullName': 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.',
  'ispb': '13486793',
  'name': 'BRL TRUST DTVM SA'},
 {'code': 331,
  'fullName': 'OSLO CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A',
  'ispb': '13673855',
  'name': 'OSLO CAPITAL DTVM SA'},
 {'code': 119,
  'fullName': 'Banco Western Union do Brasil S.A.',
  'ispb': '13720915',
  'name': 'BCO WESTERN UNION'},
 {'code': 396,
  'fullName': 'MAGALUPAY INSTITUIÇÃO DE PAGAMENTO S.A.',
  'ispb': '13884775',
  'name': 'MAGALUPAY'},
 {'code': 509,
  'fullName': 'CELCOIN INSTITUICAO DE PAGAMENTO S.A.',
  'ispb': '13935893',
  'name': 'CELCOIN IP S.A.'},
 {'code': 254,
  'fullName': 'PARANÁ BANCO S.A.',
  'ispb': '14388334',
  'name': 'PARANA BCO S.A.'},
 {'code': 268,
  'fullName': 'BARI COMPANHIA HIPOTECÁRIA',
  'ispb': '14511781',
  'name': 'BARI CIA HIPOTECÁRIA'},
 {'code': 401,
  'fullName': 'IUGU INSTITUIÇÃO DE PAGAMENTO S.A.',
  'ispb': '15111975',
  'name': 'IUGU IP S.A.'},
 {'code': 107,
  'fullName': 'Banco Bocom BBM S.A.',
  'ispb': '15114366',
  'name': 'BCO BOCOM BBM S.A.'},

In [15]:
import json 

with open("bancos.json", "w") as arquivo:
    json.dump(bancos, arquivo)

In [16]:
import json 

with open("bancos.json", "r") as arquivo:
    bancos_arquivo = json.load(arquivo)

In [17]:
bancos_arquivo[:5]

[{'ispb': '00000000',
  'name': 'BCO DO BRASIL S.A.',
  'code': 1,
  'fullName': 'Banco do Brasil S.A.'},
 {'ispb': '00000208',
  'name': 'BRB - BCO DE BRASILIA S.A.',
  'code': 70,
  'fullName': 'BRB - BANCO DE BRASILIA S.A.'},
 {'ispb': '00038121',
  'name': 'Selic',
  'code': None,
  'fullName': 'Banco Central do Brasil - Selic'},
 {'ispb': '00038166',
  'name': 'Bacen',
  'code': None,
  'fullName': 'Banco Central do Brasil'},
 {'ispb': '00122327',
  'name': 'SANTINVEST S.A. - CFI',
  'code': 539,
  'fullName': 'SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTOS'}]

In [28]:
import pandas as pd 

df_bancos = pd.DataFrame(bancos)

df_bancos.head()

,ispb,name,code,fullName
0,00000000,BCO DO BRASIL S.A.,1.0,Banco do Brasil S.A.
1,00000208,BRB - BCO DE BRASILIA S.A.,70.0,BRB - BANCO DE BRASILIA S.A.
2,00038121,Selic,NaN,Banco Central do Brasil - Selic
3,00038166,Bacen,NaN,Banco Central do Brasil
4,00122327,SANTINVEST S.A. - CFI,539.0,"SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INV..."

In [29]:
df_bancos.tail()

,ispb,name,code,fullName
467,92702067,BCO DO ESTADO DO RS S.A.,41.0,Banco do Estado do Rio Grande do Sul S.A.
468,92825397,COOPCRECE,543.0,COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS EL...
469,92874270,BCO DIGIMAIS S.A.,654.0,BANCO DIGIMAIS S.A.
470,92894922,BANCO ORIGINAL,212.0,Banco Original S.A.
471,94968518,EFX CC LTDA.,289.0,EFX CORRETORA DE CÂMBIO LTDA.

In [20]:
df_bancos.info()

<class 'pandas.DataFrame'>
RangeIndex: 472 entries, 0 to 471
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ispb      472 non-null    str
 1   name      472 non-null    str
 2   code      464 non-null    float64
 3   fullName  472 non-null    str
dtypes: float64(1), str(3)
memory usage: 14.9 KB

In [21]:
df_bancos.iloc[-2:]

         ispb            name   code                       fullName
470  92894922  BANCO ORIGINAL  212.0            Banco Original S.A.
471  94968518    EFX CC LTDA.  289.0  EFX CORRETORA DE CÂMBIO LTDA.

In [25]:
df_bancos[df_bancos["code"].isnull()]

,ispb,name,code,fullName
2,00038121,Selic,NaN,Banco Central do Brasil - Selic
3,00038166,Bacen,NaN,Banco Central do Brasil
10,00394460,STN,NaN,Secretaria do Tesouro Nacional - STN
42,02992335,CIP SA Siloc,NaN,CIP S.A
61,04391007,CIP SA Sitraf,NaN,CIP S.A
191,23399607,CERC S.A.,NaN,CERC S.A.
211,29011780,CIP SA C3,NaN,CIP S.A
215,30498377,CSDBR,NaN,CSD CENTRAL DE SERVICOS DE REGISTRO E DEPOSITO...

In [30]:
df_bancos = df_bancos.dropna(subset=["code"])

df_bancos.head()

,ispb,name,code,fullName
0,00000000,BCO DO BRASIL S.A.,1.0,Banco do Brasil S.A.
1,00000208,BRB - BCO DE BRASILIA S.A.,70.0,BRB - BANCO DE BRASILIA S.A.
4,00122327,SANTINVEST S.A. - CFI,539.0,"SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INV..."
5,00204963,CCR SEARA,430.0,COOPERATIVA DE CREDITO RURAL SEARA - CREDISEARA
6,00250699,AGK CC S.A.,272.0,AGK CORRETORA DE CAMBIO S.A.

In [27]:
df_bancos.info()

<class 'pandas.DataFrame'>
Index: 464 entries, 0 to 471
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ispb      464 non-null    str
 1   name      464 non-null    str
 2   code      464 non-null    float64
 3   fullName  464 non-null    str
dtypes: float64(1), str(3)
memory usage: 18.1 KB

In [34]:
df_bancos["code"] = df_bancos["code"].astype(int)

df_bancos.head()

,ispb,name,code,fullName
0,00000000,BCO DO BRASIL S.A.,1,Banco do Brasil S.A.
1,00000208,BRB - BCO DE BRASILIA S.A.,70,BRB - BANCO DE BRASILIA S.A.
4,00122327,SANTINVEST S.A. - CFI,539,"SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INV..."
5,00204963,CCR SEARA,430,COOPERATIVA DE CREDITO RURAL SEARA - CREDISEARA
6,00250699,AGK CC S.A.,272,AGK CORRETORA DE CAMBIO S.A.

In [35]:
df_bancos.info()

<class 'pandas.DataFrame'>
Index: 464 entries, 0 to 471
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ispb      464 non-null    str
 1   name      464 non-null    str
 2   code      464 non-null    int64
 3   fullName  464 non-null    str
dtypes: int64(1), str(3)
memory usage: 18.1 KB

In [36]:
df_bancos.to_csv("bancos.csv", index=False)

### Usando outro endpoint da API

Um **endpoint** de uma API refere-se a um ponto específico de acesso na API para o qual as requisições podem ser feitas. Em termos mais simples, é uma URL específica da API onde você pode acessar determinados dados ou funcionalidades. Cada endpoint é associado a uma função específica, como recuperar dados, atualizar dados, deletar dados, entre outras.

In [39]:
URL_BANCO_ITAU = "https://brasilapi.com.br/api/banks/v1/341"

resposta_itau = requests.get(URL_BANCO_ITAU)

resposta_itau.status_code

200

In [40]:
resposta_itau.json()

{'ispb': '60701190',
 'name': 'ITAÚ UNIBANCO S.A.',
 'code': 341,
 'fullName': 'ITAÚ UNIBANCO S.A.'}