# Consumindo APIs simples

## Dados de DDD da BrasilAPI

In [4]:
" - ".join(["s1", "s2"])

's1 - s2'

In [1]:
import requests

In [5]:
URL_DDD = "https://brasilapi.com.br/api/ddd/v1/"

resposta_ddd_11 = requests.get("".join([URL_DDD, "11"]))

resposta_ddd_11.status_code

200

In [8]:
resposta_ddd_11.headers

{'Date': 'Thu, 16 Apr 2026 19:15:05 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'Age': '5609', 'Cache-Control': 'max-age=0, public', 'Report-To': '{"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=EdASTaQwnteoOpo1ooUFCnE2BrVcAzd55EfnxOMKFJ0fad2%2FJoKyedXcF%2FUKji8aHw%2Bt5mgD1XxcgZHXm3WFHAXFGf%2F74df%2BaO4BLNbg%2B%2BQjCb6I%2FmN5O29zPoVe7N%2F0dGZv26tZymvM4rQpX%2BHP"}]}', 'Server': 'cloudflare', 'strict-transport-security': 'max-age=63072000', 'x-matched-path': '/api/ddd/v1/[ddd]', 'x-vercel-cache': 'HIT', 'x-vercel-id': 'gru1::sfo1::n6svn-1776366905495-717739d9a896', 'cf-cache-status': 'DYNAMIC', 'Nel': '{"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}', 'etag': 'W/"17tbthf3rtvpm"', 'Content-Encoding': 'gzip', 'CF-RAY': '9ed58447495ba51d-GRU', 'alt-svc': 'h3=":443"; ma=86400'}

In [ ]:
resposta_ddd_11.json()

{'state': 'SP',
 'cities': ['EMBU',
  'VÁRZEA PAULISTA',
  'VARGEM GRANDE PAULISTA',
  'VARGEM',
  'TUIUTI',
  'TABOÃO DA SERRA',
  'SUZANO',
  'SÃO ROQUE',
  'SÃO PAULO',
  'SÃO LOURENÇO DA SERRA',
  'SÃO CAETANO DO SUL',
  'SÃO BERNARDO DO CAMPO',
  'SANTO ANDRÉ',
  'SANTANA DE PARNAÍBA',
  'SANTA ISABEL',
  'SALTO',
  'SALESÓPOLIS',
  'RIO GRANDE DA SERRA',
  'RIBEIRÃO PIRES',
  'POÁ',
  'PIRAPORA DO BOM JESUS',
  'PIRACAIA',
  'PINHALZINHO',
  'PEDRA BELA',
  'OSASCO',
  'NAZARÉ PAULISTA',
  'MORUNGABA',
  'MOGI DAS CRUZES',
  'MAUÁ',
  'MAIRIPORÃ',
  'MAIRINQUE',
  'JUQUITIBA',
  'JUNDIAÍ',
  'JOANÓPOLIS',
  'JARINU',
  'JANDIRA',
  'ITUPEVA',
  'ITU',
  'ITATIBA',
  'ITAQUAQUECETUBA',
  'ITAPEVI',
  'ITAPECERICA DA SERRA',
  'IGARATÁ',
  'GUARULHOS',
  'GUARAREMA',
  'FRANCO DA ROCHA',
  'FRANCISCO MORATO',
  'FERRAZ DE VASCONCELOS',
  'EMBU-GUAÇU',
  'DIADEMA',
  'COTIA',
  'CARAPICUÍBA',
  'CAMPO LIMPO PAULISTA',
  'CAJAMAR',
  'CAIEIRAS',
  'CABREÚVA',
  'BRAGANÇA PAULISTA',
  'BOM JESUS DOS PERDÕES',
  'BIRITIBA-MIRIM',
  'BARUERI',
  'ATIBAIA',
  'ARUJÁ',
  'ARAÇARIGUAMA',
  'ALUMÍNIO']}

In [7]:
from pprint import pprint

pprint(resposta_ddd_11.json())

{'cities': ['EMBU',
            'VÁRZEA PAULISTA',
            'VARGEM GRANDE PAULISTA',
            'VARGEM',
            'TUIUTI',
            'TABOÃO DA SERRA',
            'SUZANO',
            'SÃO ROQUE',
            'SÃO PAULO',
            'SÃO LOURENÇO DA SERRA',
            'SÃO CAETANO DO SUL',
            'SÃO BERNARDO DO CAMPO',
            'SANTO ANDRÉ',
            'SANTANA DE PARNAÍBA',
            'SANTA ISABEL',
            'SALTO',
            'SALESÓPOLIS',
            'RIO GRANDE DA SERRA',
            'RIBEIRÃO PIRES',
            'POÁ',
            'PIRAPORA DO BOM JESUS',
            'PIRACAIA',
            'PINHALZINHO',
            'PEDRA BELA',
            'OSASCO',
            'NAZARÉ PAULISTA',
            'MORUNGABA',
            'MOGI DAS CRUZES',
            'MAUÁ',
            'MAIRIPORÃ',
            'MAIRINQUE',
            'JUQUITIBA',
            'JUNDIAÍ',
            'JOANÓPOLIS',
            'JARINU',
            'JANDIRA',
            'ITUPEVA',
            'ITU',
            'ITATIBA',
            'ITAQUAQUECETUBA',
            'ITAPEVI',
            'ITAPECERICA DA SERRA',
            'IGARATÁ',
            'GUARULHOS',
            'GUARAREMA',
            'FRANCO DA ROCHA',
            'FRANCISCO MORATO',
            'FERRAZ DE VASCONCELOS',
            'EMBU-GUAÇU',
            'DIADEMA',
            'COTIA',
            'CARAPICUÍBA',
            'CAMPO LIMPO PAULISTA',
            'CAJAMAR',
            'CAIEIRAS',
            'CABREÚVA',
            'BRAGANÇA PAULISTA',
            'BOM JESUS DOS PERDÕES',
            'BIRITIBA-MIRIM',
            'BARUERI',
            'ATIBAIA',
            'ARUJÁ',
            'ARAÇARIGUAMA',
            'ALUMÍNIO'],
 'state': 'SP'}

In [12]:
# criando dataframe para armazenar os dados do DDD 21
import pandas as pd 

ddd_11 = pd.DataFrame(resposta_ddd_11.json()).assign(ddd=11)

ddd_11

   state                  cities  ddd
0     SP                    EMBU   11
1     SP         VÁRZEA PAULISTA   11
2     SP  VARGEM GRANDE PAULISTA   11
3     SP                  VARGEM   11
4     SP                  TUIUTI   11
..   ...                     ...  ...
59    SP                 BARUERI   11
60    SP                 ATIBAIA   11
61    SP                   ARUJÁ   11
62    SP            ARAÇARIGUAMA   11
63    SP                ALUMÍNIO   11

[64 rows x 3 columns]

**ATENÇÃO**: Sempre verifique a documentação da API para verificar se há limites de requisições por minuto ou de loops.

In [14]:
# verificando o status code de buscas por DDD entre 20 e 30
for ddd in range (11, 31):
    resposta = requests.get("".join([URL_DDD, str(ddd)]))
    print(f"DDD: {ddd} - Status code: {resposta.status_code}")

DDD: 11 - Status code: 200
DDD: 12 - Status code: 200
DDD: 13 - Status code: 200
DDD: 14 - Status code: 200
DDD: 15 - Status code: 200
DDD: 16 - Status code: 200
DDD: 17 - Status code: 200
DDD: 18 - Status code: 200
DDD: 19 - Status code: 200
DDD: 20 - Status code: 404
DDD: 21 - Status code: 200
DDD: 22 - Status code: 200
DDD: 23 - Status code: 404
DDD: 24 - Status code: 200
DDD: 25 - Status code: 404
DDD: 26 - Status code: 404
DDD: 27 - Status code: 200
DDD: 28 - Status code: 200
DDD: 29 - Status code: 404
DDD: 30 - Status code: 404

In [20]:
# para os status code 200, vamos armazenar os dados em um dataframe
df_ddd = pd.DataFrame()

for ddd in range(11, 30):
    resposta = requests.get("".join([URL_DDD, str(ddd)]))
    if resposta.status_code == 200:
        df_ddd = pd.concat([df_ddd, pd.DataFrame(resposta.json()).assign(ddd=ddd)])

df_ddd

# verificando o status code e adicionando ao dataframe com o método concat

   state                  cities  ddd
0     SP                    EMBU   11
1     SP         VÁRZEA PAULISTA   11
2     SP  VARGEM GRANDE PAULISTA   11
3     SP                  VARGEM   11
4     SP                  TUIUTI   11
..   ...                     ...  ...
23    ES      BOM JESUS DO NORTE   28
24    ES         ATILIO VIVACQUA   28
25    ES                  APIACÁ   28
26    ES                ANCHIETA   28
27    ES                  ALEGRE   28

[815 rows x 3 columns]

In [25]:
df_ddd = df_ddd.reset_index(drop=True)

df_ddd

    state                  cities  ddd
0      SP                    EMBU   11
1      SP         VÁRZEA PAULISTA   11
2      SP  VARGEM GRANDE PAULISTA   11
3      SP                  VARGEM   11
4      SP                  TUIUTI   11
..    ...                     ...  ...
810    ES      BOM JESUS DO NORTE   28
811    ES         ATILIO VIVACQUA   28
812    ES                  APIACÁ   28
813    ES                ANCHIETA   28
814    ES                  ALEGRE   28

[815 rows x 3 columns]

In [26]:
df_ddd.info()

<class 'pandas.DataFrame'>
RangeIndex: 815 entries, 0 to 814
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   state   815 non-null    str
 1   cities  815 non-null    str
 2   ddd     815 non-null    int64
dtypes: int64(1), str(2)
memory usage: 19.2 KB

## Dados de Municípios da BrasilAPI

In [29]:
URL_MUNICIPIOS_SP = "https://brasilapi.com.br/api/ibge/municipios/v1/SP?providers=dados-abertos-br,gov,wikipedia"

resposta_municipios_sp = requests.get(URL_MUNICIPIOS_SP)

resposta_municipios_sp.status_code

200

In [ ]:
resposta_municipios_sp.json()

[{'nome': 'ADAMANTINA', 'codigo_ibge': '3500105'},
 {'nome': 'ADOLFO', 'codigo_ibge': '3500204'},
 {'nome': 'AGUAÍ', 'codigo_ibge': '3500303'},
 {'nome': 'ÁGUAS DA PRATA', 'codigo_ibge': '3500402'},
 {'nome': 'ÁGUAS DE LINDÓIA', 'codigo_ibge': '3500501'},
 {'nome': 'ÁGUAS DE SANTA BÁRBARA', 'codigo_ibge': '3500550'},
 {'nome': 'ÁGUAS DE SÃO PEDRO', 'codigo_ibge': '3500600'},
 {'nome': 'AGUDOS', 'codigo_ibge': '3500709'},
 {'nome': 'ALAMBARI', 'codigo_ibge': '3500758'},
 {'nome': 'ALFREDO MARCONDES', 'codigo_ibge': '3500808'},
 {'nome': 'ALTAIR', 'codigo_ibge': '3500907'},
 {'nome': 'ALTINÓPOLIS', 'codigo_ibge': '3501004'},
 {'nome': 'ALTO ALEGRE', 'codigo_ibge': '3501103'},
 {'nome': 'ALUMÍNIO', 'codigo_ibge': '3501152'},
 {'nome': 'ÁLVARES FLORENCE', 'codigo_ibge': '3501202'},
 {'nome': 'ÁLVARES MACHADO', 'codigo_ibge': '3501301'},
 {'nome': 'ÁLVARO DE CARVALHO', 'codigo_ibge': '3501400'},
 {'nome': 'ALVINLÂNDIA', 'codigo_ibge': '3501509'},
 {'nome': 'AMERICANA', 'codigo_ibge': '3501608'},
 {'nome': 'AMÉRICO BRASILIENSE', 'codigo_ibge': '3501707'},
 {'nome': 'AMÉRICO DE CAMPOS', 'codigo_ibge': '3501806'},
 {'nome': 'AMPARO', 'codigo_ibge': '3501905'},
 {'nome': 'ANALÂNDIA', 'codigo_ibge': '3502002'},
 {'nome': 'ANDRADINA', 'codigo_ibge': '3502101'},
 {'nome': 'ANGATUBA', 'codigo_ibge': '3502200'},
 {'nome': 'ANHEMBI', 'codigo_ibge': '3502309'},
 {'nome': 'ANHUMAS', 'codigo_ibge': '3502408'},
 {'nome': 'APARECIDA', 'codigo_ibge': '3502507'},
 {'nome': "APARECIDA D'OESTE", 'codigo_ibge': '3502606'},
 {'nome': 'APIAÍ', 'codigo_ibge': '3502705'},
 {'nome': 'ARAÇARIGUAMA', 'codigo_ibge': '3502754'},
 {'nome': 'ARAÇATUBA', 'codigo_ibge': '3502804'},
 {'nome': 'ARAÇOIABA DA SERRA', 'codigo_ibge': '3502903'},
 {'nome': 'ARAMINA', 'codigo_ibge': '3503000'},
 {'nome': 'ARANDU', 'codigo_ibge': '3503109'},
 {'nome': 'ARAPEÍ', 'codigo_ibge': '3503158'},
 {'nome': 'ARARAQUARA', 'codigo_ibge': '3503208'},
 {'nome': 'ARARAS', 'codigo_ibge': '3503307'},
 {'nome': 'ARCO-ÍRIS', 'codigo_ibge': '3503356'},
 {'nome': 'AREALVA', 'codigo_ibge': '3503406'},
 {'nome': 'AREIAS', 'codigo_ibge': '3503505'},
 {'nome': 'AREIÓPOLIS', 'codigo_ibge': '3503604'},
 {'nome': 'ARIRANHA', 'codigo_ibge': '3503703'},
 {'nome': 'ARTUR NOGUEIRA', 'codigo_ibge': '3503802'},
 {'nome': 'ARUJÁ', 'codigo_ibge': '3503901'},
 {'nome': 'ASPÁSIA', 'codigo_ibge': '3503950'},
 {'nome': 'ASSIS', 'codigo_ibge': '3504008'},
 {'nome': 'ATIBAIA', 'codigo_ibge': '3504107'},
 {'nome': 'AURIFLAMA', 'codigo_ibge': '3504206'},
 {'nome': 'AVAÍ', 'codigo_ibge': '3504305'},
 {'nome': 'AVANHANDAVA', 'codigo_ibge': '3504404'},
 {'nome': 'AVARÉ', 'codigo_ibge': '3504503'},
 {'nome': 'BADY BASSITT', 'codigo_ibge': '3504602'},
 {'nome': 'BALBINOS', 'codigo_ibge': '3504701'},
 {'nome': 'BÁLSAMO', 'codigo_ibge': '3504800'},
 {'nome': 'BANANAL', 'codigo_ibge': '3504909'},
 {'nome': 'BARÃO DE ANTONINA', 'codigo_ibge': '3505005'},
 {'nome': 'BARBOSA', 'codigo_ibge': '3505104'},
 {'nome': 'BARIRI', 'codigo_ibge': '3505203'},
 {'nome': 'BARRA BONITA', 'codigo_ibge': '3505302'},
 {'nome': 'BARRA DO CHAPÉU', 'codigo_ibge': '3505351'},
 {'nome': 'BARRA DO TURVO', 'codigo_ibge': '3505401'},
 {'nome': 'BARRETOS', 'codigo_ibge': '3505500'},
 {'nome': 'BARRINHA', 'codigo_ibge': '3505609'},
 {'nome': 'BARUERI', 'codigo_ibge': '3505708'},
 {'nome': 'BASTOS', 'codigo_ibge': '3505807'},
 {'nome': 'BATATAIS', 'codigo_ibge': '3505906'},
 {'nome': 'BAURU', 'codigo_ibge': '3506003'},
 {'nome': 'BEBEDOURO', 'codigo_ibge': '3506102'},
 {'nome': 'BENTO DE ABREU', 'codigo_ibge': '3506201'},
 {'nome': 'BERNARDINO DE CAMPOS', 'codigo_ibge': '3506300'},
 {'nome': 'BERTIOGA', 'codigo_ibge': '3506359'},
 {'nome': 'BILAC', 'codigo_ibge': '3506409'},
 {'nome': 'BIRIGUI', 'codigo_ibge': '3506508'},
 {'nome': 'BIRITIBA MIRIM', 'codigo_ibge': '3506607'},
 {'nome': 'BOA ESPERANÇA DO SUL', 'codigo_ibge': '3506706'},
 {'nome': 'BOCAINA', 'codigo_ibge': '3506805'},
 {'nome': 'BOFETE', 'codigo_ibge': '3506904'},
 {'nome': 'BOITUVA', 'codigo_ibge': '3507001'},
 {'nome': 'BOM JESUS DOS PERDÕES', 'codigo_ibge': '3507100'},
 {'nome': 'BOM SUCESSO DE ITARARÉ', 'codigo_ibge': '3507159'},
 {'nome': 'BORÁ', 'codigo_ibge': '3507209'},
 {'nome': 'BORACÉIA', 'codigo_ibge': '3507308'},
 {'nome': 'BORBOREMA', 'codigo_ibge': '3507407'},
 {'nome': 'BOREBI', 'codigo_ibge': '3507456'},
 {'nome': 'BOTUCATU', 'codigo_ibge': '3507506'},
 {'nome': 'BRAGANÇA PAULISTA', 'codigo_ibge': '3507605'},
 {'nome': 'BRAÚNA', 'codigo_ibge': '3507704'},
 {'nome': 'BREJO ALEGRE', 'codigo_ibge': '3507753'},
 {'nome': 'BRODOWSKI', 'codigo_ibge': '3507803'},
 {'nome': 'BROTAS', 'codigo_ibge': '3507902'},
 {'nome': 'BURI', 'codigo_ibge': '3508009'},
 {'nome': 'BURITAMA', 'codigo_ibge': '3508108'},
 {'nome': 'BURITIZAL', 'codigo_ibge': '3508207'},
 {'nome': 'CABRÁLIA PAULISTA', 'codigo_ibge': '3508306'},
 {'nome': 'CABREÚVA', 'codigo_ibge': '3508405'},
 {'nome': 'CAÇAPAVA', 'codigo_ibge': '3508504'},
 {'nome': 'CACHOEIRA PAULISTA', 'codigo_ibge': '3508603'},
 {'nome': 'CACONDE', 'codigo_ibge': '3508702'},
 {'nome': 'CAFELÂNDIA', 'codigo_ibge': '3508801'},
 {'nome': 'CAIABU', 'codigo_ibge': '3508900'},
 {'nome': 'CAIEIRAS', 'codigo_ibge': '3509007'},
 {'nome': 'CAIUÁ', 'codigo_ibge': '3509106'},
 {'nome': 'CAJAMAR', 'codigo_ibge': '3509205'},
 {'nome': 'CAJATI', 'codigo_ibge': '3509254'},
 {'nome': 'CAJOBI', 'codigo_ibge': '3509304'},
 {'nome': 'CAJURU', 'codigo_ibge': '3509403'},
 {'nome': 'CAMPINA DO MONTE ALEGRE', 'codigo_ibge': '3509452'},
 {'nome': 'CAMPINAS', 'codigo_ibge': '3509502'},
 {'nome': 'CAMPO LIMPO PAULISTA', 'codigo_ibge': '3509601'},
 {'nome': 'CAMPOS DO JORDÃO', 'codigo_ibge': '3509700'},
 {'nome': 'CAMPOS NOVOS PAULISTA', 'codigo_ibge': '3509809'},
 {'nome': 'CANANÉIA', 'codigo_ibge': '3509908'},
 {'nome': 'CANAS', 'codigo_ibge': '3509957'},
 {'nome': 'CÂNDIDO MOTA', 'codigo_ibge': '3510005'},
 {'nome': 'CÂNDIDO RODRIGUES', 'codigo_ibge': '3510104'},
 {'nome': 'CANITAR', 'codigo_ibge': '3510153'},
 {'nome': 'CAPÃO BONITO', 'codigo_ibge': '3510203'},
 {'nome': 'CAPELA DO ALTO', 'codigo_ibge': '3510302'},
 {'nome': 'CAPIVARI', 'codigo_ibge': '3510401'},
 {'nome': 'CARAGUATATUBA', 'codigo_ibge': '3510500'},
 {'nome': 'CARAPICUÍBA', 'codigo_ibge': '3510609'},
 {'nome': 'CARDOSO', 'codigo_ibge': '3510708'},
 {'nome': 'CASA BRANCA', 'codigo_ibge': '3510807'},
 {'nome': 'CÁSSIA DOS COQUEIROS', 'codigo_ibge': '3510906'},
 {'nome': 'CASTILHO', 'codigo_ibge': '3511003'},
 {'nome': 'CATANDUVA', 'codigo_ibge': '3511102'},
 {'nome': 'CATIGUÁ', 'codigo_ibge': '3511201'},
 {'nome': 'CEDRAL', 'codigo_ibge': '3511300'},
 {'nome': 'CERQUEIRA CÉSAR', 'codigo_ibge': '3511409'},
 {'nome': 'CERQUILHO', 'codigo_ibge': '3511508'},
 {'nome': 'CESÁRIO LANGE', 'codigo_ibge': '3511607'},
 {'nome': 'CHARQUEADA', 'codigo_ibge': '3511706'},
 {'nome': 'CLEMENTINA', 'codigo_ibge': '3511904'},
 {'nome': 'COLINA', 'codigo_ibge': '3512001'},
 {'nome': 'COLÔMBIA', 'codigo_ibge': '3512100'},
 {'nome': 'CONCHAL', 'codigo_ibge': '3512209'},
 {'nome': 'CONCHAS', 'codigo_ibge': '3512308'},
 {'nome': 'CORDEIRÓPOLIS', 'codigo_ibge': '3512407'},
 {'nome': 'COROADOS', 'codigo_ibge': '3512506'},
 {'nome': 'CORONEL MACEDO', 'codigo_ibge': '3512605'},
 {'nome': 'CORUMBATAÍ', 'codigo_ibge': '3512704'},
 {'nome': 'COSMÓPOLIS', 'codigo_ibge': '3512803'},
 {'nome': 'COSMORAMA', 'codigo_ibge': '3512902'},
 {'nome': 'COTIA', 'codigo_ibge': '3513009'},
 {'nome': 'CRAVINHOS', 'codigo_ibge': '3513108'},
 {'nome': 'CRISTAIS PAULISTA', 'codigo_ibge': '3513207'},
 {'nome': 'CRUZÁLIA', 'codigo_ibge': '3513306'},
 {'nome': 'CRUZEIRO', 'codigo_ibge': '3513405'},
 {'nome': 'CUBATÃO', 'codigo_ibge': '3513504'},
 {'nome': 'CUNHA', 'codigo_ibge': '3513603'},
 {'nome': 'DESCALVADO', 'codigo_ibge': '3513702'},
 {'nome': 'DIADEMA', 'codigo_ibge': '3513801'},
 {'nome': 'DIRCE REIS', 'codigo_ibge': '3513850'},
 {'nome': 'DIVINOLÂNDIA', 'codigo_ibge': '3513900'},
 {'nome': 'DOBRADA', 'codigo_ibge': '3514007'},
 {'nome': 'DOIS CÓRREGOS', 'codigo_ibge': '3514106'},
 {'nome': 'DOLCINÓPOLIS', 'codigo_ibge': '3514205'},
 {'nome': 'DOURADO', 'codigo_ibge': '3514304'},
 {'nome': 'DRACENA', 'codigo_ibge': '3514403'},
 {'nome': 'DUARTINA', 'codigo_ibge': '3514502'},
 {'nome': 'DUMONT', 'codigo_ibge': '3514601'},
 {'nome': 'ECHAPORÃ', 'codigo_ibge': '3514700'},
 {'nome': 'ELDORADO', 'codigo_ibge': '3514809'},
 {'nome': 'ELIAS FAUSTO', 'codigo_ibge': '3514908'},
 {'nome': 'ELISIÁRIO', 'codigo_ibge': '3514924'},
 {'nome': 'EMBAÚBA', 'codigo_ibge': '3514957'},
 {'nome': 'EMBU DAS ARTES', 'codigo_ibge': '3515004'},
 {'nome': 'EMBU-GUAÇU', 'codigo_ibge': '3515103'},
 {'nome': 'EMILIANÓPOLIS', 'codigo_ibge': '3515129'},
 {'nome': 'ENGENHEIRO COELHO', 'codigo_ibge': '3515152'},
 {'nome': 'ESPÍRITO SANTO DO PINHAL', 'codigo_ibge': '3515186'},
 {'nome': 'ESPÍRITO SANTO DO TURVO', 'codigo_ibge': '3515194'},
 {'nome': "ESTRELA D'OESTE", 'codigo_ibge': '3515202'},
 {'nome': 'ESTRELA DO NORTE', 'codigo_ibge': '3515301'},
 {'nome': 'EUCLIDES DA CUNHA PAULISTA', 'codigo_ibge': '3515350'},
 {'nome': 'FARTURA', 'codigo_ibge': '3515400'},
 {'nome': 'FERNANDÓPOLIS', 'codigo_ibge': '3515509'},
 {'nome': 'FERNANDO PRESTES', 'codigo_ibge': '3515608'},
 {'nome': 'FERNÃO', 'codigo_ibge': '3515657'},
 {'nome': 'FERRAZ DE VASCONCELOS', 'codigo_ibge': '3515707'},
 {'nome': 'FLORA RICA', 'codigo_ibge': '3515806'},
 {'nome': 'FLOREAL', 'codigo_ibge': '3515905'},
 {'nome': 'FLÓRIDA PAULISTA', 'codigo_ibge': '3516002'},
 {'nome': 'FLORÍNEA', 'codigo_ibge': '3516101'},
 {'nome': 'FRANCA', 'codigo_ibge': '3516200'},
 {'nome': 'FRANCISCO MORATO', 'codigo_ibge': '3516309'},
 {'nome': 'FRANCO DA ROCHA', 'codigo_ibge': '3516408'},
 {'nome': 'GABRIEL MONTEIRO', 'codigo_ibge': '3516507'},
 {'nome': 'GÁLIA', 'codigo_ibge': '3516606'},
 {'nome': 'GARÇA', 'codigo_ibge': '3516705'},
 {'nome': 'GASTÃO VIDIGAL', 'codigo_ibge': '3516804'},
 {'nome': 'GAVIÃO PEIXOTO', 'codigo_ibge': '3516853'},
 {'nome': 'GENERAL SALGADO', 'codigo_ibge': '3516903'},
 {'nome': 'GETULINA', 'codigo_ibge': '3517000'},
 {'nome': 'GLICÉRIO', 'codigo_ibge': '3517109'},
 {'nome': 'GUAIÇARA', 'codigo_ibge': '3517208'},
 {'nome': 'GUAIMBÊ', 'codigo_ibge': '3517307'},
 {'nome': 'GUAÍRA', 'codigo_ibge': '3517406'},
 {'nome': 'GUAPIAÇU', 'codigo_ibge': '3517505'},
 {'nome': 'GUAPIARA', 'codigo_ibge': '3517604'},
 {'nome': 'GUARÁ', 'codigo_ibge': '3517703'},
 {'nome': 'GUARAÇAÍ', 'codigo_ibge': '3517802'},
 {'nome': 'GUARACI', 'codigo_ibge': '3517901'},
 {'nome': "GUARANI D'OESTE", 'codigo_ibge': '3518008'},
 {'nome': 'GUARANTÃ', 'codigo_ibge': '3518107'},
 {'nome': 'GUARARAPES', 'codigo_ibge': '3518206'},
 {'nome': 'GUARAREMA', 'codigo_ibge': '3518305'},
 {'nome': 'GUARATINGUETÁ', 'codigo_ibge': '3518404'},
 {'nome': 'GUAREÍ', 'codigo_ibge': '3518503'},
 {'nome': 'GUARIBA', 'codigo_ibge': '3518602'},
 {'nome': 'GUARUJÁ', 'codigo_ibge': '3518701'},
 {'nome': 'GUARULHOS', 'codigo_ibge': '3518800'},
 {'nome': 'GUATAPARÁ', 'codigo_ibge': '3518859'},
 {'nome': 'GUZOLÂNDIA', 'codigo_ibge': '3518909'},
 {'nome': 'HERCULÂNDIA', 'codigo_ibge': '3519006'},
 {'nome': 'HOLAMBRA', 'codigo_ibge': '3519055'},
 {'nome': 'HORTOLÂNDIA', 'codigo_ibge': '3519071'},
 {'nome': 'IACANGA', 'codigo_ibge': '3519105'},
 {'nome': 'IACRI', 'codigo_ibge': '3519204'},
 {'nome': 'IARAS', 'codigo_ibge': '3519253'},
 {'nome': 'IBATÉ', 'codigo_ibge': '3519303'},
 {'nome': 'IBIRÁ', 'codigo_ibge': '3519402'},
 {'nome': 'IBIRAREMA', 'codigo_ibge': '3519501'},
 {'nome': 'IBITINGA', 'codigo_ibge': '3519600'},
 {'nome': 'IBIÚNA', 'codigo_ibge': '3519709'},
 {'nome': 'ICÉM', 'codigo_ibge': '3519808'},
 {'nome': 'IEPÊ', 'codigo_ibge': '3519907'},
 {'nome': 'IGARAÇU DO TIETÊ', 'codigo_ibge': '3520004'},
 {'nome': 'IGARAPAVA', 'codigo_ibge': '3520103'},
 {'nome': 'IGARATÁ', 'codigo_ibge': '3520202'},
 {'nome': 'IGUAPE', 'codigo_ibge': '3520301'},
 {'nome': 'ILHABELA', 'codigo_ibge': '3520400'},
 {'nome': 'ILHA COMPRIDA', 'codigo_ibge': '3520426'},
 {'nome': 'ILHA SOLTEIRA', 'codigo_ibge': '3520442'},
 {'nome': 'INDAIATUBA', 'codigo_ibge': '3520509'},
 {'nome': 'INDIANA', 'codigo_ibge': '3520608'},
 {'nome': 'INDIAPORÃ', 'codigo_ibge': '3520707'},
 {'nome': 'INÚBIA PAULISTA', 'codigo_ibge': '3520806'},
 {'nome': 'IPAUSSU', 'codigo_ibge': '3520905'},
 {'nome': 'IPERÓ', 'codigo_ibge': '3521002'},
 {'nome': 'IPEÚNA', 'codigo_ibge': '3521101'},
 {'nome': 'IPIGUÁ', 'codigo_ibge': '3521150'},
 {'nome': 'IPORANGA', 'codigo_ibge': '3521200'},
 {'nome': 'IPUÃ', 'codigo_ibge': '3521309'},
 {'nome': 'IRACEMÁPOLIS', 'codigo_ibge': '3521408'},
 {'nome': 'IRAPUÃ', 'codigo_ibge': '3521507'},
 {'nome': 'IRAPURU', 'codigo_ibge': '3521606'},
 {'nome': 'ITABERÁ', 'codigo_ibge': '3521705'},
 {'nome': 'ITAÍ', 'codigo_ibge': '3521804'},
 {'nome': 'ITAJOBI', 'codigo_ibge': '3521903'},
 {'nome': 'ITAJU', 'codigo_ibge': '3522000'},
 {'nome': 'ITANHAÉM', 'codigo_ibge': '3522109'},
 {'nome': 'ITAOCA', 'codigo_ibge': '3522158'},
 {'nome': 'ITAPECERICA DA SERRA', 'codigo_ibge': '3522208'},
 {'nome': 'ITAPETININGA', 'codigo_ibge': '3522307'},
 {'nome': 'ITAPEVA', 'codigo_ibge': '3522406'},
 {'nome': 'ITAPEVI', 'codigo_ibge': '3522505'},
 {'nome': 'ITAPIRA', 'codigo_ibge': '3522604'},
 {'nome': 'ITAPIRAPUÃ PAULISTA', 'codigo_ibge': '3522653'},
 {'nome': 'ITÁPOLIS', 'codigo_ibge': '3522703'},
 {'nome': 'ITAPORANGA', 'codigo_ibge': '3522802'},
 {'nome': 'ITAPUÍ', 'codigo_ibge': '3522901'},
 {'nome': 'ITAPURA', 'codigo_ibge': '3523008'},
 {'nome': 'ITAQUAQUECETUBA', 'codigo_ibge': '3523107'},
 {'nome': 'ITARARÉ', 'codigo_ibge': '3523206'},
 {'nome': 'ITARIRI', 'codigo_ibge': '3523305'},
 {'nome': 'ITATIBA', 'codigo_ibge': '3523404'},
 {'nome': 'ITATINGA', 'codigo_ibge': '3523503'},
 {'nome': 'ITIRAPINA', 'codigo_ibge': '3523602'},
 {'nome': 'ITIRAPUÃ', 'codigo_ibge': '3523701'},
 {'nome': 'ITOBI', 'codigo_ibge': '3523800'},
 {'nome': 'ITU', 'codigo_ibge': '3523909'},
 {'nome': 'ITUPEVA', 'codigo_ibge': '3524006'},
 {'nome': 'ITUVERAVA', 'codigo_ibge': '3524105'},
 {'nome': 'JABORANDI', 'codigo_ibge': '3524204'},
 {'nome': 'JABOTICABAL', 'codigo_ibge': '3524303'},
 {'nome': 'JACAREÍ', 'codigo_ibge': '3524402'},
 {'nome': 'JACI', 'codigo_ibge': '3524501'},
 {'nome': 'JACUPIRANGA', 'codigo_ibge': '3524600'},
 {'nome': 'JAGUARIÚNA', 'codigo_ibge': '3524709'},
 {'nome': 'JALES', 'codigo_ibge': '3524808'},
 {'nome': 'JAMBEIRO', 'codigo_ibge': '3524907'},
 {'nome': 'JANDIRA', 'codigo_ibge': '3525003'},
 {'nome': 'JARDINÓPOLIS', 'codigo_ibge': '3525102'},
 {'nome': 'JARINU', 'codigo_ibge': '3525201'},
 {'nome': 'JAÚ', 'codigo_ibge': '3525300'},
 {'nome': 'JERIQUARA', 'codigo_ibge': '3525409'},
 {'nome': 'JOANÓPOLIS', 'codigo_ibge': '3525508'},
 {'nome': 'JOÃO RAMALHO', 'codigo_ibge': '3525607'},
 {'nome': 'JOSÉ BONIFÁCIO', 'codigo_ibge': '3525706'},
 {'nome': 'JÚLIO MESQUITA', 'codigo_ibge': '3525805'},
 {'nome': 'JUMIRIM', 'codigo_ibge': '3525854'},
 {'nome': 'JUNDIAÍ', 'codigo_ibge': '3525904'},
 {'nome': 'JUNQUEIRÓPOLIS', 'codigo_ibge': '3526001'},
 {'nome': 'JUQUIÁ', 'codigo_ibge': '3526100'},
 {'nome': 'JUQUITIBA', 'codigo_ibge': '3526209'},
 {'nome': 'LAGOINHA', 'codigo_ibge': '3526308'},
 {'nome': 'LARANJAL PAULISTA', 'codigo_ibge': '3526407'},
 {'nome': 'LAVÍNIA', 'codigo_ibge': '3526506'},
 {'nome': 'LAVRINHAS', 'codigo_ibge': '3526605'},
 {'nome': 'LEME', 'codigo_ibge': '3526704'},
 {'nome': 'LENÇÓIS PAULISTA', 'codigo_ibge': '3526803'},
 {'nome': 'LIMEIRA', 'codigo_ibge': '3526902'},
 {'nome': 'LINDÓIA', 'codigo_ibge': '3527009'},
 {'nome': 'LINS', 'codigo_ibge': '3527108'},
 {'nome': 'LORENA', 'codigo_ibge': '3527207'},
 {'nome': 'LOURDES', 'codigo_ibge': '3527256'},
 {'nome': 'LOUVEIRA', 'codigo_ibge': '3527306'},
 {'nome': 'LUCÉLIA', 'codigo_ibge': '3527405'},
 {'nome': 'LUCIANÓPOLIS', 'codigo_ibge': '3527504'},
 {'nome': 'LUÍS ANTÔNIO', 'codigo_ibge': '3527603'},
 {'nome': 'LUIZIÂNIA', 'codigo_ibge': '3527702'},
 {'nome': 'LUPÉRCIO', 'codigo_ibge': '3527801'},
 {'nome': 'LUTÉCIA', 'codigo_ibge': '3527900'},
 {'nome': 'MACATUBA', 'codigo_ibge': '3528007'},
 {'nome': 'MACAUBAL', 'codigo_ibge': '3528106'},
 {'nome': 'MACEDÔNIA', 'codigo_ibge': '3528205'},
 {'nome': 'MAGDA', 'codigo_ibge': '3528304'},
 {'nome': 'MAIRINQUE', 'codigo_ibge': '3528403'},
 {'nome': 'MAIRIPORÃ', 'codigo_ibge': '3528502'},
 {'nome': 'MANDURI', 'codigo_ibge': '3528601'},
 {'nome': 'MARABÁ PAULISTA', 'codigo_ibge': '3528700'},
 {'nome': 'MARACAÍ', 'codigo_ibge': '3528809'},
 {'nome': 'MARAPOAMA', 'codigo_ibge': '3528858'},
 {'nome': 'MARIÁPOLIS', 'codigo_ibge': '3528908'},
 {'nome': 'MARÍLIA', 'codigo_ibge': '3529005'},
 {'nome': 'MARINÓPOLIS', 'codigo_ibge': '3529104'},
 {'nome': 'MARTINÓPOLIS', 'codigo_ibge': '3529203'},
 {'nome': 'MATÃO', 'codigo_ibge': '3529302'},
 {'nome': 'MAUÁ', 'codigo_ibge': '3529401'},
 {'nome': 'MENDONÇA', 'codigo_ibge': '3529500'},
 {'nome': 'MERIDIANO', 'codigo_ibge': '3529609'},
 {'nome': 'MESÓPOLIS', 'codigo_ibge': '3529658'},
 {'nome': 'MIGUELÓPOLIS', 'codigo_ibge': '3529708'},
 {'nome': 'MINEIROS DO TIETÊ', 'codigo_ibge': '3529807'},
 {'nome': 'MIRACATU', 'codigo_ibge': '3529906'},
 {'nome': 'MIRA ESTRELA', 'codigo_ibge': '3530003'},
 {'nome': 'MIRANDÓPOLIS', 'codigo_ibge': '3530102'},
 {'nome': 'MIRANTE DO PARANAPANEMA', 'codigo_ibge': '3530201'},
 {'nome': 'MIRASSOL', 'codigo_ibge': '3530300'},
 {'nome': 'MIRASSOLÂNDIA', 'codigo_ibge': '3530409'},
 {'nome': 'MOCOCA', 'codigo_ibge': '3530508'},
 {'nome': 'MOGI DAS CRUZES', 'codigo_ibge': '3530607'},
 {'nome': 'MOGI GUAÇU', 'codigo_ibge': '3530706'},
 {'nome': 'MOGI MIRIM', 'codigo_ibge': '3530805'},
 {'nome': 'MOMBUCA', 'codigo_ibge': '3530904'},
 {'nome': 'MONÇÕES', 'codigo_ibge': '3531001'},
 {'nome': 'MONGAGUÁ', 'codigo_ibge': '3531100'},
 {'nome': 'MONTE ALEGRE DO SUL', 'codigo_ibge': '3531209'},
 {'nome': 'MONTE ALTO', 'codigo_ibge': '3531308'},
 {'nome': 'MONTE APRAZÍVEL', 'codigo_ibge': '3531407'},
 {'nome': 'MONTE AZUL PAULISTA', 'codigo_ibge': '3531506'},
 {'nome': 'MONTE CASTELO', 'codigo_ibge': '3531605'},
 {'nome': 'MONTEIRO LOBATO', 'codigo_ibge': '3531704'},
 {'nome': 'MONTE MOR', 'codigo_ibge': '3531803'},
 {'nome': 'MORRO AGUDO', 'codigo_ibge': '3531902'},
 {'nome': 'MORUNGABA', 'codigo_ibge': '3532009'},
 {'nome': 'MOTUCA', 'codigo_ibge': '3532058'},
 {'nome': 'MURUTINGA DO SUL', 'codigo_ibge': '3532108'},
 {'nome': 'NANTES', 'codigo_ibge': '3532157'},
 {'nome': 'NARANDIBA', 'codigo_ibge': '3532207'},
 {'nome': 'NATIVIDADE DA SERRA', 'codigo_ibge': '3532306'},
 {'nome': 'NAZARÉ PAULISTA', 'codigo_ibge': '3532405'},
 {'nome': 'NEVES PAULISTA', 'codigo_ibge': '3532504'},
 {'nome': 'NHANDEARA', 'codigo_ibge': '3532603'},
 {'nome': 'NIPOÃ', 'codigo_ibge': '3532702'},
 {'nome': 'NOVA ALIANÇA', 'codigo_ibge': '3532801'},
 {'nome': 'NOVA CAMPINA', 'codigo_ibge': '3532827'},
 {'nome': 'NOVA CANAÃ PAULISTA', 'codigo_ibge': '3532843'},
 {'nome': 'NOVA CASTILHO', 'codigo_ibge': '3532868'},
 {'nome': 'NOVA EUROPA', 'codigo_ibge': '3532900'},
 {'nome': 'NOVA GRANADA', 'codigo_ibge': '3533007'},
 {'nome': 'NOVA GUATAPORANGA', 'codigo_ibge': '3533106'},
 {'nome': 'NOVA INDEPENDÊNCIA', 'codigo_ibge': '3533205'},
 {'nome': 'NOVAIS', 'codigo_ibge': '3533254'},
 {'nome': 'NOVA LUZITÂNIA', 'codigo_ibge': '3533304'},
 {'nome': 'NOVA ODESSA', 'codigo_ibge': '3533403'},
 {'nome': 'NOVO HORIZONTE', 'codigo_ibge': '3533502'},
 {'nome': 'NUPORANGA', 'codigo_ibge': '3533601'},
 {'nome': 'OCAUÇU', 'codigo_ibge': '3533700'},
 {'nome': 'ÓLEO', 'codigo_ibge': '3533809'},
 {'nome': 'OLÍMPIA', 'codigo_ibge': '3533908'},
 {'nome': 'ONDA VERDE', 'codigo_ibge': '3534005'},
 {'nome': 'ORIENTE', 'codigo_ibge': '3534104'},
 {'nome': 'ORINDIÚVA', 'codigo_ibge': '3534203'},
 {'nome': 'ORLÂNDIA', 'codigo_ibge': '3534302'},
 {'nome': 'OSASCO', 'codigo_ibge': '3534401'},
 {'nome': 'OSCAR BRESSANE', 'codigo_ibge': '3534500'},
 {'nome': 'OSVALDO CRUZ', 'codigo_ibge': '3534609'},
 {'nome': 'OURINHOS', 'codigo_ibge': '3534708'},
 {'nome': 'OUROESTE', 'codigo_ibge': '3534757'},
 {'nome': 'OURO VERDE', 'codigo_ibge': '3534807'},

In [32]:
# convertendo para dataframe

df_sp = pd.DataFrame(resposta_municipios_sp.json())

df_sp

                 nome codigo_ibge
0          ADAMANTINA     3500105
1              ADOLFO     3500204
2               AGUAÍ     3500303
3      ÁGUAS DA PRATA     3500402
4    ÁGUAS DE LINDÓIA     3500501
..                ...         ...
640        VOTORANTIM     3557006
641       VOTUPORANGA     3557105
642          ZACARIAS     3557154
643         CHAVANTES     3557204
644      ESTIVA GERBI     3557303

[645 rows x 2 columns]

In [33]:
df_sp.info()

<class 'pandas.DataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nome         645 non-null    str
 1   codigo_ibge  645 non-null    str
dtypes: str(2)
memory usage: 10.2 KB